// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/audit": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает историю изменений конфигурации для namespace.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "Получить аудит namespace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.AuditResponse"
                        }
                    },
                    "400": {
                        "description": "namespace is required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cache/flush": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Публикует событие принудительного перечитывания конфигурации для namespace.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "legacy-cache"
                ],
                "summary": "Опубликовать flush-событие",
                "parameters": [
                    {
                        "description": "Данные flush-запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.FlushRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/http.FlushResponse"
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает все конфигурационные параметры для указанного namespace.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "legacy-config"
                ],
                "summary": "Получить все конфиги namespace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.ConfigNamespaceResponse"
                        }
                    },
                    "400": {
                        "description": "namespace is required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Экспортирует конфигурацию namespace. При format=yaml возвращает тот же набор данных в YAML.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "legacy-config"
                ],
                "summary": "Экспорт конфигурации",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Формат ответа: json или yaml",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ExportResponse"
                        }
                    },
                    "400": {
                        "description": "namespace is required or unsupported format",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config/import": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Импортирует конфигурацию из JSON или YAML payload и публикует событие обновления.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "legacy-config"
                ],
                "summary": "Импорт конфигурации",
                "parameters": [
                    {
                        "description": "Данные импорта конфигурации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ConfigImportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.ConfigUpdateResponse"
                        }
                    },
                    "400": {
                        "description": "bad request or validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "version conflict",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config/update": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет несколько конфигурационных параметров в namespace и публикует событие обновления.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "legacy-config"
                ],
                "summary": "Массовое обновление конфигурации",
                "parameters": [
                    {
                        "description": "Данные обновления конфигурации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ConfigUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.ConfigUpdateResponse"
                        }
                    },
                    "400": {
                        "description": "bad request or validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "version conflict",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/configs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает все namespace, в которых есть config-значения, и полный набор config-элементов по каждому namespace.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Получить все namespace и все config-значения",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.ConfigCatalogResponse"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/configs/{namespace}/{key}": {
            "get": {
                "description": "Возвращает конфигурационный параметр по namespace и key.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Получить конфигурационный параметр",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ключ параметра",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ConfigItem"
                        }
                    },
                    "404": {
                        "description": "config item not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Сохраняет конфигурационный параметр в Redis и публикует событие обновления для SDK.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Создать или обновить конфигурационный параметр",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ключ параметра",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные конфигурационного параметра",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.PutConfigKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ConfigItem"
                        }
                    },
                    "400": {
                        "description": "bad request or validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "version conflict",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет параметр из Redis и публикует событие обновления.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Удалить конфигурационный параметр",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ключ параметра",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Кто выполняет удаление",
                        "name": "updatedBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "config item not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/features/{namespace}/{key}": {
            "get": {
                "description": "Возвращает состояние feature toggle по namespace и key.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "features"
                ],
                "summary": "Получить feature toggle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ключ feature toggle",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.FeatureToggle"
                        }
                    },
                    "404": {
                        "description": "config item not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Сохраняет feature toggle в Redis и публикует событие обновления для SDK.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "features"
                ],
                "summary": "Создать или обновить feature toggle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ключ feature toggle",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные feature toggle",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.PutFeatureKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.FeatureToggle"
                        }
                    },
                    "400": {
                        "description": "bad request or validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "version conflict",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет feature toggle из Redis и публикует событие обновления.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "features"
                ],
                "summary": "Удалить feature toggle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ключ feature toggle",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Кто выполняет удаление",
                        "name": "updatedBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "config item not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Возвращает статус работы сервиса и доступность Redis.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Проверка состояния Admin API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.HealthResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Возвращает метрики в формате Prometheus.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Метрики Admin API",
                "responses": {
                    "200": {
                        "description": "Prometheus metrics",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AuditRecord": {
            "type": "object",
            "properties": {
                "isSecret": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "newValue": {
                    "type": "string"
                },
                "oldValue": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "domain.ConfigImportItem": {
            "type": "object",
            "properties": {
                "expectedVersion": {
                    "type": "integer"
                },
                "isSecret": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "domain.ConfigImportRequest": {
            "type": "object",
            "properties": {
                "dryRun": {
                    "type": "boolean"
                },
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ConfigUpdateEntry"
                    }
                },
                "items": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/domain.ConfigImportItem"
                    }
                },
                "namespace": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                }
            }
        },
        "domain.ConfigItem": {
            "type": "object",
            "properties": {
                "isSecret": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "domain.ConfigUpdateEntry": {
            "type": "object",
            "properties": {
                "expectedVersion": {
                    "type": "integer"
                },
                "isSecret": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "domain.ConfigUpdateRequest": {
            "type": "object",
            "properties": {
                "dryRun": {
                    "type": "boolean"
                },
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ConfigUpdateEntry"
                    }
                },
                "namespace": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                }
            }
        },
        "domain.ExportResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ConfigItem"
                    }
                },
                "namespace": {
                    "type": "string"
                }
            }
        },
        "domain.FeatureToggle": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "domain.FlushRequest": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                }
            }
        },
        "http.AuditResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.AuditRecord"
                    }
                },
                "namespace": {
                    "type": "string",
                    "example": "payments"
                }
            }
        },
        "http.ConfigCatalogResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ExportResponse"
                    }
                },
                "namespaces": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "payments",
                        "demo-service"
                    ]
                }
            }
        },
        "http.ConfigNamespaceResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ConfigItem"
                    }
                },
                "namespace": {
                    "type": "string",
                    "example": "payments"
                }
            }
        },
        "http.ConfigUpdateResponse": {
            "type": "object",
            "properties": {
                "dryRun": {
                    "type": "boolean",
                    "example": false
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ConfigItem"
                    }
                },
                "namespace": {
                    "type": "string",
                    "example": "payments"
                }
            }
        },
        "http.FlushResponse": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string",
                    "example": "payments"
                },
                "status": {
                    "type": "string",
                    "example": "flush published"
                }
            }
        },
        "http.HealthResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "dial tcp 127.0.0.1:6379: connect: connection refused"
                },
                "redis": {
                    "type": "string",
                    "example": "up"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "http.PutConfigKeyRequest": {
            "type": "object",
            "properties": {
                "expectedVersion": {
                    "type": "integer",
                    "example": 0
                },
                "isSecret": {
                    "type": "boolean",
                    "example": false
                },
                "type": {
                    "type": "string",
                    "example": "int"
                },
                "updatedBy": {
                    "type": "string",
                    "example": "admin@example.com"
                },
                "value": {
                    "type": "string",
                    "example": "15"
                }
            }
        },
        "http.PutFeatureKeyRequest": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean",
                    "example": true
                },
                "expectedVersion": {
                    "type": "integer",
                    "example": 0
                },
                "updatedBy": {
                    "type": "string",
                    "example": "admin@example.com"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Введите токен в формате: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Remote Config System Admin API",
	Description:      "Admin API для управления конфигурациями и feature toggles с поддержкой hot-reload.\nЗначения сохраняются в Redis, после чего публикуется событие обновления через Redis Pub/Sub.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
