// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/audit": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает историю изменений конфигурации для namespace.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "Получить аудит namespace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.AuditResponse"
                        }
                    },
                    "400": {
                        "description": "namespace is required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cache/flush": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Does not modify stored config values. It only publishes a Redis Pub/Sub flush event for the namespace so SDK clients can perform a full namespace reload.\nПубликует событие принудительного перечитывания конфигурации для namespace.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "legacy-cache"
                ],
                "summary": "Опубликовать flush-событие",
                "parameters": [
                    {
                        "description": "Данные flush-запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.FlushRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/http.FlushResponse"
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает все конфигурационные параметры для указанного namespace.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "legacy-config"
                ],
                "summary": "Получить все конфиги namespace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.ConfigNamespaceResponse"
                        }
                    },
                    "400": {
                        "description": "namespace is required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Exports config items for one namespace as JSON or YAML. Secret items are masked as \"****\", so export output is useful for inspection but is not a lossless backup for secret values and cannot be imported back to restore secrets as-is.\nЭкспортирует конфигурацию namespace. При format=yaml возвращает тот же набор данных в YAML.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "legacy-config"
                ],
                "summary": "Экспорт конфигурации",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Формат ответа: json или yaml",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ExportResponse"
                        }
                    },
                    "400": {
                        "description": "namespace is required or unsupported format",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config/import": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Merge semantics: import converts the payload to the same update flow as /config/update. Only items present in the request are updated or created; existing config items omitted from the payload are left unchanged. The client does not send expectedVersion; the server computes each next version. The namespace is protected by a Redis lock while the import runs. The request is atomic for the whole payload and publishes one Redis Pub/Sub update event with all changed keys. When dryRun=true, nothing is persisted and no event is published.\nИмпортирует конфигурацию из JSON или YAML payload и публикует событие обновления.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "legacy-config"
                ],
                "summary": "Импорт конфигурации",
                "parameters": [
                    {
                        "description": "Данные импорта конфигурации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ConfigImportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.ConfigUpdateResponse"
                        }
                    },
                    "400": {
                        "description": "bad request or validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "423": {
                        "description": "namespace is locked by another write operation",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/config/update": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Merge semantics: only entries from the request are updated or created, and config items omitted from the request are left unchanged. The client does not send expectedVersion; the server computes each next version. The namespace is protected by a Redis lock while the bulk operation runs. The request succeeds atomically for all entries or fails without partial writes. On success each changed item gets version+1 and the API publishes one Redis Pub/Sub event with the list of changed keys. When dryRun=true, the request validates and computes versions but does not persist data, create audit records, or publish events.\nОбновляет несколько конфигурационных параметров в namespace и публикует событие обновления.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "legacy-config"
                ],
                "summary": "Массовое обновление конфигурации",
                "parameters": [
                    {
                        "description": "Данные обновления конфигурации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ConfigUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.ConfigUpdateResponse"
                        }
                    },
                    "400": {
                        "description": "bad request or validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "423": {
                        "description": "namespace is locked by another write operation",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/configs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает все namespace, в которых есть config-значения, и полный набор config-элементов по каждому namespace.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Получить все namespace и все config-значения",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.ConfigCatalogResponse"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/configs/{namespace}/{key}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает конфигурационный параметр по namespace и key.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Получить конфигурационный параметр",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ключ параметра",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ConfigItem"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "config item not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upserts a single config item. The client does not send expectedVersion; the server takes a per-resource Redis lock, checks the namespace bulk lock, reads the current value atomically, creates version 1 for a new key, or stores current version + 1 for an existing key. Concurrent writes to the same key, or writes while a bulk update/import holds the namespace lock, return 423 Locked instead of 409 because the resource is temporarily locked rather than version-conflicted. Only the addressed key is changed; other keys in the namespace are untouched. A successful write publishes one Redis Pub/Sub update event for that key.\nСохраняет конфигурационный параметр в Redis и публикует событие обновления для SDK.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Создать или обновить конфигурационный параметр",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ключ параметра",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные конфигурационного параметра",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.PutConfigKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ConfigItem"
                        }
                    },
                    "400": {
                        "description": "bad request or validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "423": {
                        "description": "resource or namespace is locked by another write operation",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет параметр из Redis и публикует событие обновления.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "Удалить конфигурационный параметр",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ключ параметра",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Кто выполняет удаление",
                        "name": "updatedBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "config item not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/features/{namespace}/{key}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает состояние feature toggle по namespace и key.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "features"
                ],
                "summary": "Получить feature toggle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ключ feature toggle",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.FeatureToggle"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "config item not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upserts a single feature toggle. The client does not send expectedVersion; the server takes a per-resource Redis lock, reads the current value atomically, creates version 1 for a new toggle, or stores current version + 1 for an existing toggle. Concurrent writes to the same toggle return 423 Locked instead of 409 because the resource is temporarily locked rather than version-conflicted. Only the addressed toggle is changed; other toggles are untouched. A successful write publishes one Redis Pub/Sub update event for that key.\nСохраняет feature toggle в Redis и публикует событие обновления для SDK.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "features"
                ],
                "summary": "Создать или обновить feature toggle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ключ feature toggle",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные feature toggle",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.PutFeatureKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.FeatureToggle"
                        }
                    },
                    "400": {
                        "description": "bad request or validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "423": {
                        "description": "resource is locked by another write operation",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет feature toggle из Redis и публикует событие обновления.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "features"
                ],
                "summary": "Удалить feature toggle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace сервиса",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ключ feature toggle",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Кто выполняет удаление",
                        "name": "updatedBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "config item not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Возвращает статус работы сервиса и доступность Redis.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Проверка состояния Admin API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.HealthResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает метрики в формате Prometheus.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Метрики Admin API",
                "responses": {
                    "200": {
                        "description": "Prometheus metrics",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "missing bearer token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "forbidden",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AuditRecord": {
            "type": "object",
            "properties": {
                "isSecret": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "newValue": {
                    "type": "string"
                },
                "oldValue": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "domain.ConfigImportItem": {
            "type": "object",
            "properties": {
                "isSecret": {
                    "type": "boolean",
                    "example": false
                },
                "type": {
                    "type": "string",
                    "example": "int"
                },
                "value": {}
            }
        },
        "domain.ConfigImportRequest": {
            "type": "object",
            "properties": {
                "dryRun": {
                    "type": "boolean",
                    "example": false
                },
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ConfigUpdateEntry"
                    }
                },
                "items": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/domain.ConfigImportItem"
                    }
                },
                "namespace": {
                    "type": "string",
                    "example": "demo-service"
                },
                "updatedBy": {
                    "type": "string",
                    "example": "admin@example.com"
                }
            }
        },
        "domain.ConfigItem": {
            "type": "object",
            "properties": {
                "isSecret": {
                    "type": "boolean",
                    "example": false
                },
                "key": {
                    "type": "string",
                    "example": "discount.percent"
                },
                "namespace": {
                    "type": "string",
                    "example": "demo-service"
                },
                "type": {
                    "type": "string",
                    "example": "int"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string",
                    "example": "admin@example.com"
                },
                "value": {
                    "type": "string",
                    "example": "25"
                },
                "version": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "domain.ConfigUpdateEntry": {
            "type": "object",
            "properties": {
                "isSecret": {
                    "type": "boolean",
                    "example": false
                },
                "key": {
                    "type": "string",
                    "example": "discount.percent"
                },
                "type": {
                    "type": "string",
                    "example": "int"
                },
                "value": {
                    "type": "string",
                    "example": "25"
                }
            }
        },
        "domain.ConfigUpdateRequest": {
            "type": "object",
            "properties": {
                "dryRun": {
                    "type": "boolean",
                    "example": false
                },
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ConfigUpdateEntry"
                    }
                },
                "namespace": {
                    "type": "string",
                    "example": "demo-service"
                },
                "updatedBy": {
                    "type": "string",
                    "example": "admin@example.com"
                }
            }
        },
        "domain.ExportResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ConfigItem"
                    }
                },
                "namespace": {
                    "type": "string"
                }
            }
        },
        "domain.FeatureToggle": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "domain.FlushRequest": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string",
                    "example": "demo-service"
                },
                "updatedBy": {
                    "type": "string",
                    "example": "admin@example.com"
                }
            }
        },
        "http.AuditResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.AuditRecord"
                    }
                },
                "namespace": {
                    "type": "string",
                    "example": "payments"
                }
            }
        },
        "http.ConfigCatalogResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ExportResponse"
                    }
                },
                "namespaces": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "payments",
                        "demo-service"
                    ]
                }
            }
        },
        "http.ConfigNamespaceResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ConfigItem"
                    }
                },
                "namespace": {
                    "type": "string",
                    "example": "payments"
                }
            }
        },
        "http.ConfigUpdateResponse": {
            "type": "object",
            "properties": {
                "dryRun": {
                    "type": "boolean",
                    "example": false
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ConfigItem"
                    }
                },
                "namespace": {
                    "type": "string",
                    "example": "payments"
                }
            }
        },
        "http.FlushResponse": {
            "type": "object",
            "properties": {
                "namespace": {
                    "type": "string",
                    "example": "payments"
                },
                "status": {
                    "type": "string",
                    "example": "flush published"
                }
            }
        },
        "http.HealthResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "dial tcp 127.0.0.1:6379: connect: connection refused"
                },
                "redis": {
                    "type": "string",
                    "example": "up"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "http.PutConfigKeyRequest": {
            "type": "object",
            "properties": {
                "isSecret": {
                    "type": "boolean",
                    "example": false
                },
                "type": {
                    "type": "string",
                    "example": "int"
                },
                "updatedBy": {
                    "type": "string",
                    "example": "admin@example.com"
                },
                "value": {
                    "type": "string",
                    "example": "15"
                }
            }
        },
        "http.PutFeatureKeyRequest": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean",
                    "example": true
                },
                "updatedBy": {
                    "type": "string",
                    "example": "admin@example.com"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Введите токен в формате: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Remote Config System Admin API",
	Description:      "Admin API для управления конфигурациями и feature toggles с поддержкой hot-reload.\nЗначения сохраняются в Redis, после чего публикуется событие обновления через Redis Pub/Sub.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
